<div class="row black-text">
	<?php if (isset($form)): ?>
		<?php $form->prepare();?>
		<?php echo $this->form()->openTag($form);?>
    		 <?php foreach ($form->getElements() as $element):?>
    		 <?php $attributes = $element->getAttributes();?>
    		 <?php if ($attributes && $attributes['type']=='submit'):?>
    		 
    		   <a class="btn teal white-text" href="<?php echo $url?>">Затвори</a>
    		    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                    <i class="material-icons right">send</i>
                </button>
    		   <?php echo $this->form_row($element);?>
    		
    		 <?php elseif($attributes && $attributes['type']=='checkbox'):?>
                <p>
                  <?php echo $this->formelement($element);?>
                  <label for="<?php $attributes['id']?>"> <?php echo $element->getLabel();?></label>
                </p>
    		 <?php else:?>
    			<?php echo $this->form_row($element);?>
    		 <?php endif;?>
             <?php endforeach;?>
             
		<?php echo $this->form()->closeTag();?>	
    <?php endif; ?>
</div>


<script>
$(document).ready(function() {
    $('select').material_select();
    $('.datepicker').pickadate({
        format:"yyyy-mm-dd",
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15 // Creates a dropdown of 15 years to control year
      });
  });
</script>