<?php echo $this->doctype(); ?>

<html  itemscope itemtype="http://schema.org/Article" prefix="og: http://ogp.me/ns#" lang="en">
    <head>
        <meta charset="utf-8">
        <link href='http://fonts.googleapis.com/css?family=Ruslan+Display&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/materialize.css')
		?>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/materialize.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="row">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
