<div class="row container col m6">
	<div class="collection with-header">
		<h5 class="collection-header">Администрация</h5>
    		<a class="collection-item" href="<?php echo $this->url('Contract');?>">Договори</a>
    		<a class="collection-item" href="<?php echo $this->url('Property');?>">Имоти</a>
    		<a class="collection-item" href="<?php echo $this->url('Ouner');?>">Собственици</a>
	</div>
</div>
<div class="row container col m6">
	<h5>Потребителски справки</h5>
</div>